# Generated by Django 5.0.2 on 2024-02-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chic_photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiospace',
            name='photoDirectory',
        ),
        migrations.AddField(
            model_name='studiospace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/'),
        ),
    ]
