# Generated by Django 5.0.2 on 2024-02-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chic_photo', '0002_remove_studiospace_photodirectory_studiospace_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='serviceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chic_photo.service'),
        ),
    ]
