# Generated by Django 5.0.2 on 2024-02-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chic_photo', '0004_remove_photographer_portfolioid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(db_default=True),
        ),
    ]
